name: Pandoc

on: push
permissions:
  contents: write

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    container:
      image: pandoc/core:latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          pandoc -s -o index.html --metadata title="Skattunier" index.md
          git config --global user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generate index.html"
          git push
