name: Pandoc

on: push
permissions:
  contents: write

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker://pandoc/core:latest
        with:
          args: -s -o index.html index.md

      - uses: EndBug/add-and-commit@v9
        with: 
          default_author: github_actions
